config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'welcome/index'
  get 'admin/index'
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'carts/show'

  devise_for :users
  resources :users
  resources :products
  resources :categories
  resources :groups

  resources :orders do
    patch :update_status, on: :member
  end

  get '/orders/status/:id', to: 'orders#status', as: 'show_order_status'
  
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name,  :presence => true

  has_many :groups, :dependent => :destroy
end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name,  :presence => true
  validates :description, :presence => true
  validates :category_id,  :presence => true

  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates :image, :attachment_presence => true
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  belongs_to :category
  has_many :products, :dependent => :destroy

end

app/models/order.rb
class Order < ActiveRecord::Base
  #validates :card_number, presence: true, length: { is: 16 }
  #validates :card_code, presence: true, length: { is: 3 }
  #validates :card_number, length: { is: 16 }
  #validates :card_code, length: { is: 3 }

  belongs_to :order_status

  has_many :order_items, :dependent => :delete_all
  before_create :set_order_status, :set_defaul_values
  before_save :update_subtotal, :update_tax, :update_total


  def self.get_orders(admin,user)
    if (admin == user || user.employee == true)
      return Order.all
    else
      return Order.where("user_id = ?", user.id)
    end
  end

  def update_order(order_status_id)
    self[:order_status_id] = order_status_id

    if self.save
      return true
    else
      return false
    end
  end

  def update_product_invetory(order)
    order.order_items.each do |order_item|
      order_item.product.count = order_item.product.count - order_item.quantity
      order_item.product.save
    end
  end

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  def set_user(user)
    self[:user_id] = user.id
  end

  def get_user
    user = User.find(self[:user_id])
    return user
  end


  def incriment_order_status
    status = self.order_status_id
    status = status + 1
    self.order_status_id = status
  end

  private
  def set_order_status
    self.order_status_id = 1
  end

  def set_defaul_values
    self.card_number = "0000000000000000"
    self.card_code = "000"
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end

  def update_tax
    self[:tax] = self[:subtotal] * 0.06
  end

  def update_total
    self[:total] = self[:subtotal] + self[:tax]
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.default_price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name,  :presence => true
  validates :group_id,  :presence => true
  validates :description, :presence => true
  validates :default_price, :presence => true
  validates :count, :presence => true

  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }

  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]


  belongs_to :group
  has_many :order_items



end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, :last_name, :street, :city, :zip, :phone, :presence => true

  has_many :orders
  belongs_to :state

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  #--- Check if user is the Admin ---
  def is_admin
    if @admin == current_user
      return true
    else
      return false
    end
  end
  #----------------------------------

  #--- Check if user is the Admin ---
  def is_employee
    if current_user.employee == true
      return true
    else
      return false
    end
  end
  #----------------------------------



end

app/helpers/card_helper.rb
module CardHelper

def card_months
  [
    ['Jan', '01'],
    ['Feb', '02'],
    ['March', '03'],
    ['April', '04'],
    ['May', '05'],
    ['June', '06'],
    ['July', '07'],
    ['Aug', '08'],
    ['Sep', '09'],
    ['Oct', '10'],
    ['Nov', '11'],
    ['Dec', '12']
  ]
end

def card_years
  [
    ['2015'],
    ['2016'],
    ['2017'],
    ['2018'],
    ['2019'],
    ['2020'],
    ['2021'],
    ['2022'],
    ['2023']
  ]
end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
    count: resource.errors.count,
    resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-block"> <button type="button"
      class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  #---- Print Product Price ----
  def print_price
    
  end
  #-----------------------------
end

app/helpers/states_helper.rb
module StatesHelper

  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<div class="container">
  <fieldset>
  <h1 class="page-header text-center">Configuration Manager</h1>
  <div class="row">
    <div class="col-sm-6">
      <%= link_to 'Manage Users', users_path, :class => "btn btn-lg btn-block btn btn-default" %>
        </div>
        <div class="col-sm-6">
          <%= link_to 'Manage Categories', categories_path, :class => "btn btn-lg btn-block btn-default" %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6">
            <%= link_to 'Manage Products', products_path, :class => "btn btn-lg btn-block btn-default" %>
          </div>
          <div class="col-sm-6">
            <%= link_to 'Manage Groups', groups_path, :class => "btn btn-lg btn-block btn-default" %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6">
            <%= link_to 'Manage Orders', orders_path, :class => "btn btn-lg btn-block btn-default" %>
          </div>
          <div class="col-sm-6">
          </div>
        </div>
  </fieldset>
</div>

app/views/layouts/_cart_text.html.erb
<li>
  <div class="cart-text">
<%#= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )",
cart_path, class: "btn btn-link" %>
<%= link_to "Cart (#{current_order.order_items.size})",
cart_path, class: "btn btn-link" %>
  </div>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Pizza Corner LLC <%="\u00A9"%> <%=Time.now.year %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_industry_links.html.erb
<% @category_links.each do |category| %>
<li><%= link_to category.name, category %></li>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0
navbar-fixed-top
%>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse ">
      <ul class="nav navbar-nav">
        <%= render 'layouts/industry_links' %>
      </ul>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <ul class="nav navbar-nav">
    <%= render 'layouts/cart_text' %>
  </ul>

  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><%= link_to 'Edit account', edit_user_registration_path %></li>
      <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
      <li><%= link_to 'My Account', user_path(current_user) %></li>
      <% if is_admin || is_employee %>
      <li><%= link_to 'App Manager', admin_index_path %></li>
      <% else %>
      <li><%= link_to 'My Orders', orders_path %></li>
      <% end %>
      <% else %>
      <li><%= link_to 'Sign in', new_user_session_path %></li>
      <li><%= link_to 'Sign up', new_user_registration_path %></li>
    </ul>
  </li>
</ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pizza Corner LLC" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Pizza Corner" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!--insert the Stripe JavaScript partial as needed -->
    <%= yield(:head) %>

  </head>
  <body>
    <%= render 'layouts/messages' %>

    
    <%= image_tag "pizza_header.jpg", :width => "80%" %>

    <header>
      <%= render 'layouts/navigation' %>
    </header>


    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>