config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'welcome/index'
  get 'admin/index'
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'carts/show'

  devise_for :users
  resources :users
  resources :products
  resources :categories
  resources :groups

  resources :orders do
    patch :update_status, on: :member
  end

  get '/orders/status/:id', to: 'orders#status', as: 'show_order_status'
  
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name,  :presence => true
  validates :description, :presence => true
  validates :category_id,  :presence => true

  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates :image, :attachment_presence => true
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  belongs_to :category
  has_many :products, :dependent => :destroy

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    unless @admin == current_user
      redirect_to root_path, :alert => "Access denied."
    end
    
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    #Order Item for product
    @order_item = current_order.order_items.new
  end

  # GET /groups/new
  def new
    unless @admin == current_user
      redirect_to root_path, :alert => "Access denied."
    end

    @group = Group.new
  end

  # GET /groups/1/edit
  def edit

    #--Authorize--
    unless @admin == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

  # POST /groups
  # POST /groups.json
  def create

    @group = Group.new(group_params)


    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @group }

      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update

    respond_to do |format|
      if @group.update(group_params)

        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    if @admin == current_user


      @group.destroy
      respond_to do |format|
        format.html { redirect_to (groups_url), notice: 'Group was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_path, :alert => "Access denied."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description, :category_id, :image)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="form">
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.order('name ASC').all, :id, :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-default", 'data-disable-with' => "Please wait.." %>
  </div>
<% end %>
</div>

app/views/groups/_group.html.erb
<td><%= group.name %></td>
<td><%= group.description %></td>
<td><%#= group.category.name %></td>
<td>
  <% if group.image_file_name.present? %>
  <%#= image_tag group.image.url, :size => :med %>
  <%=link_to image_tag(group.image.url, :size => :med), group %>
  <% end %>
</td>

<%#=link_to image_tag(group.image.url, :size => :med), group %>
<%#= link_to , group, :class => "btn btn-default"  %>
<!--
<td><%= link_to 'Show', group, :class => "btn btn-default"  %></td>
<td><%= link_to 'Edit', edit_group_path(group), :class => "btn btn-default"  %></td>
<td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?'}, :class => "btn btn-default"  %></td>
-->

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %>
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Groups </h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.description %></td>
        <td><%= group.category.name %></td>
        <td><%= link_to 'Show', group, :class => "btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_group_path(group), :class => "btn btn-default" %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%#= link_to 'Back', @category,:class => "btn btn-default" %>
<%= link_to 'New Group', new_group_path,:class => "btn btn-default" %>

app/views/groups/new.html.erb
<div>
<h1>New Group</h1>
<p>
<%#= link_to 'Back', category_groups_path(@group.category), :class => "btn btn-default" %>
<%= link_to 'Back', groups_path %>
</p>
<%= render 'form' %>

</div>

app/views/groups/show.html.erb
<h3 class="text-center"><%= @group.name %></h3>

<p>
  <% if @group.image_file_name.present? %>
  <%= image_tag @group.image.url, :size => :med %>
  <% end %>
</p>

<h4 class="text-center"><%= @group.description %></h4>

<%#= render @group.products %>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
        <% @group.products.each do |product| %>
        <%= render "products/product", :product => product, :order_item =>@order_item %>
        <% end %>
    </div>
  </div>

<%#= link_to 'Edit', edit_group_path(@group) %>
<%#= link_to 'Back', groups_path %>
<%#= link_to 'Add Product', new_product_path %>