config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'welcome/index'
  get 'admin/index'
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'carts/show'

  devise_for :users
  resources :users
  resources :products
  resources :categories
  resources :groups

  resources :orders do
    patch :update_status, on: :member
  end

  get '/orders/status/:id', to: 'orders#status', as: 'show_order_status'
  
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name,  :presence => true

  has_many :groups, :dependent => :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    unless @admin == current_user
      redirect_to root_path, :alert => "Access denied."
    end
    
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    unless @admin == current_user
      redirect_to root_path, :alert => "Access denied."
    end
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    unless @admin == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    #raise params.inspect

    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    if @admin == current_user
      @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_path, :alert => "Access denied."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category_links.html.erb
<% @category_links.each do |category| %>
<%= link_to category.name, category, class: 'navbar-brand'  %>
<% end %>

app/views/categories/_form.html.erb
<div class="form">
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-default", 'data-disable-with' => "Please wait.." %>
  </div>
<% end %>
</div>

app/views/categories/_group_table.html.erb
<div class="checkout">
  <div class="row">
    <div class="column">
      <table class="table table-striped">
        <thead>
          <tr>

            <th><%= @category.name%> Type</th>
            <th>Description</th>

            <th colspan="3"></th>

          </tr>
        </thead>
        <tbody>
          <% @category.groups.each do |group| %>
          <tr>
            <%= render 'groups/group', :group => group %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category, :class => "btn btn-default"  %></td>
        <td><%= link_to 'Edit', edit_category_path(category), :class => "btn btn-default"  %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path, :class => "btn btn-default"  %>
<%= link_to 'Back', root_path, :class => "btn btn-default" %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="checkout">

<h2 class="text-center"><%= @category.name %></h2>


<!--
<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>
-->

<%#= render @category.groups %>
<%= render 'group_table' %>

<!--
<p>
<%= link_to 'Groups', groups_path %>
<%= link_to 'Back', categories_path %>
</p>
-->
</div>